[package]
name = "veda-search-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"

#v_authorization = "=0.1.2"

v_common = { package = "v-common", version = "=0.1.57" }
