[package]
name = "veda-search-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
nng = "1.0.0"
serde_json = "1.0"

v_common = { package = "v-common", version = "0.1.98" }
#v_common = { package = "v-common", path = "../../../v-common" }
