[package]
name = "veda-mstorage"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.17"
nng = "0.5.1"
serde_json = "1.0"
chrono = "0.4"
url = "2.2.2"

v_common = { package = "v-common", version = "=0.1.86" }
#v_common = { package = "v-common", path = "../../../v-common" }
