[package]
name = "veda-mstorage"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"
chrono = "0.4"
url = "2.2.0"

v_queue = "0.1.7"
v_authorization = "=0.1.1"

v_az_lmdb = { package = "v-common-az-lmdb", version = "=0.1.2" }
v_module = { package = "v-common-module", version = "=0.1.40" }
