# Файл конфигурации для фраз, которые нужно удалить из распознанного текста
# Название файла: phrases_to_remove.toml

phrases = [
    # Оригинальные фразы
    "Субтитры сделал DimaTorzok",
    "Субтитры делал DimaTorzok",
    "Субтитры добавил DimaTorzok",
    "Субтитры создавал DimaTorzok",
    "Продолжение следует ...",
    "Продолжение следует...",
    "Перевод и озвучка",
    "Спасибо за просмотр",
    "Редактор субтитров А.Семкин Корректор А.Егорова",

    # Дополнительные фразы и артефакты
    "Музыка",
    "Аплодисменты",
    "Смех",
    "Неразборчиво",
    "Шум",
    "Тишина",
    "[неразборчиво]",
    "[шум]",
    "[музыка]",
    "[аплодисменты]",
    "Говорит неразборчиво",
    "Говорит тихо",
    "Говорит громко",
    "Бормочет",
    "Вздыхает",
    "Кашляет",
    "Звуки на заднем плане",
    "Звук отключен",
    "Плохое качество звука",
    "Помехи",
    "Эхо",
    "Фоновый шум",
    "Искажение звука",
    "Прерывается",
    "Звук прерывается",
    "Непонятно",
    "Неясно",
    "Не слышно",
    "Слова неразборчивы",
    "Речь нечеткая",
    "Слова теряются",
    "*Слышны звуки*",
]
