[package]
name = "veda-webserver"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2021"

[[bin]]
name = "veda-webserver"
path = "src/lib.rs"

[dependencies]
actix = "0.10.0"
actix-rt = "1.1.1"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
actix-redis = "0.9.1"
futures = "0.3.12"
chrono = "0.4.19"
redis-async = "0.8.1"
redis = "0.19.0"
serde = "1.0.119"
serde_derive = "1.0.119"
env_logger = "0.8.2"
scan_fmt = "0.2.5"
log = "0.4.13"
rusty_tarantool = "0.2.10"
url = "2.2.0"
serde_json = "1.0.61"

v_common = { package = "v-common", version = "=0.1.107" }
#v_common = { package = "v-common", path = "../../../v-common" }
