[package]
name = "veda-ft-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"

v_module = { package = "v-common-module", version = "0.1.29" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "0.1.30" }

