[package]
name = "veda-sparql-indexer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#oxigraph = {path = "../../../oxigraph/lib", features = ["sled"]}
#oxigraph = {path = "../../../oxigraph/lib", features = ["rocksdb"]}
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
log = "0.4"
anyhow = "1"
futures = "0.3.5"
tokio = { version = "1.6.1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }

#v_common = { package = "v-common", version = "=0.1.75" }
v_common = { package = "v-common", path = "../../../v-common" }
