version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    resource_class: large
    steps:
      - checkout
      - run:
          name: "pre-install"
          command: |
           sudo apt-get clean
           sudo apt-get update
           sudo apt-get install dpkg
      - run:
          name: "Install Test Env"
          command: |
           npm install -g testcafe
           testcafe --version
      - run:
          name: "Install"
          command: |
           ./tools/install-tarantool.sh
           ./control-install.sh
           source $HOME/.cargo/env
           go version
           rustc -V
      - run:
          name: "Build"
          command: |
           source $HOME/.cargo/env
           ./build.sh
      - run:
          name: "test"
          command: |
            ./control-start.sh
            sleep 180
            cd ./source-web && npm test && cd ..
            testcafe chrome:headless qa/testcafe/testLogin.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testPerson.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testLanguage.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testComment.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testSearch.js --screenshots screens --screenshots-on-fails screens --speed 0.6
            testcafe chrome:headless qa/testcafe/testCreatingNetInterface.js --screenshots screens --screenshots-on-fails screens --speed 0.7
            testcafe chrome:headless qa/testcafe/testDeleteAndRecovery.js --screenshots screens --screenshots-on-fails screens --speed 0.7
            testcafe chrome:headless qa/testcafe/testJournal.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testRights.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testSearchRangeOfDates.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testSimpleNet.js --screenshots screens --screenshots-on-fails screens --speed 0.6
            testcafe chrome:headless qa/testcafe/testSimpleNet2.js --screenshots screens --screenshots-on-fails screens --speed 0.6
            testcafe chrome:headless qa/testcafe/testSimpleNet3.js --screenshots screens --screenshots-on-fails screens --speed 0.6
            testcafe chrome:headless qa/testcafe/testSimpleNetLowPriority.js --screenshots screens --screenshots-on-fails screens --speed 0.6
            testcafe chrome:headless qa/testcafe/testControls.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testDropDown.js --screenshots screens --screenshots-on-fails screens --speed 1
            testcafe chrome:headless qa/testcafe/testAttributiveSearch.js --screenshots screens --screenshots-on-fails screens --speed 1
      - store_artifacts:
          path: /home/circleci/project/screens

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
