version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run:
          name: "pre-install"
          command: |
            sudo apt-get clean
            sudo apt-get update
            sudo apt-get install dpkg
      - run:
          name: "Install test environment"
          command: |
            node -v
            npm install -g testcafe
            testcafe --version
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
      - run:
          name: "Install"
          command: |
            ./tools/install-tarantool.sh
            ./control-install.sh
            source $HOME/.cargo/env
            go version
            rustc -V
      - run:
          name: "Build"
          command: |
            node -v
            source $HOME/.cargo/env
            ./build.sh
      - run:
          name: "test"
          command: |
            node -v
            ./control-start.sh
            sleep 180
            cd ./source-web && npm test
      - store_artifacts:
          path: /home/circleci/project/screens

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
