[package]
name = "veda-search-index-tt"
version = "0.1.0"
authors = ["Roman Karpov <roman.karpov@gmail.com>"]
edition = "2018"

[dependencies]
clickhouse-rs = {package = "v-clickhouse-rs", version = "0.2.0-alpha.6", default-features = false, features = ["async_std"] }
futures = "0.3.5"
log = "0.4"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "1.4.0"
regex = "1"
url = "2.1.1"
bincode = "1.2.1"
serde = "1.0"

v_common = { package = "v-common", version = "=0.1.69" }
#v_common = { package = "v-common", path = "../../../v-common" }
