[package]
name = "veda-ontologist"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-ontologist"
path = "src/main.rs"

[dependencies]
log = "0.4"

v_queue = "0.1.9"

v_module = { package = "v-common-module", version = "=0.1.50" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "=0.1.51" }
