[package]
name = "veda-ontologist"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-ontologist"
path = "src/main.rs"

[dependencies]
log = "0.4"

v_queue = "0.1.9"

v_common = { package = "v-common", version = "=0.1.52" }
