[package]
name = "veda-scripts-v8"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
lazy_static = "1.4.0"
rust_decimal = "1.7.0"
align-data = "0.1.0"

v_queue = "0.1.7"

v_module = { package = "v-common-module", version = "=0.1.42" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "=0.1.45" }
v_v8 = { package = "v-common-v8", version = "0.1.57" }
