[package]
name = "veda-scripts-v8"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
lazy_static = "1.4.0"
rust_decimal = "1.7.0"

v_queue = "0.1.4"

v_module = { package = "v-common-module", version = "0.1.28" }
v_ft_xapian = { package = "v-common-ft-xapian", version = "0.1.29" }
v_v8 = { package = "v-common-v8", version = "0.1.35" }
