name: CI

on:
  push:
    branches: [ master, CI1 ]
  pull_request:
    branches: [ master, CI1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies and other required software
      - name: Install
        run: |
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install dpkg
          sudo apt-get install firefox
          npm install -g testcafe
          ./tools/install-tarantool.sh
          ./control-install.sh
          source $HOME/.cargo/env

      # Print versions for debugging
      - name: Print versions
        run: |
          node --version
          testcafe --version
          rustc -V

      # Build the project
      - name: Build
        run: |
          source $HOME/.cargo/env
          export CARGO_TARGET_DIR=$HOME/target
          ./build.sh

      # Run tests
      - name: Test
        run: |
          ./control-start.sh
          sleep 200
          #tail -n +1 ./data/tarantool/tarantool.log
          #tail -n +1 ./logs/*.log
          cd ./source-web && npm test
        # Добавим шаг для продолжения работы при сбое тестов

      # Загружаем скриншоты как артефакты (если они есть)
      - name: Upload TestCafe screenshots
        if: failure()  # Выполняется только при сбое тестов
        uses: actions/upload-artifact@v3
        with:
          name: testcafe-screenshots
          path: ./source-web/screenshots/  # Путь к папке с сохраненными скриншотами
