[package]
name = "veda-ro-storage"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"

v_common = { package = "v-common", version = "0.1.51" }
